In [1]:
#numpy concat, stack

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 


[1 2 3 4 5 6]


In [2]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

print("arr1=", arr1) 

arr2 = np.array([[5, 6], [7, 8]])

print("arr2=", arr2) 

print("after concatenation =")

arr = np.concatenate((arr1, arr2), axis=1) #0=row, 1=col

print(arr) 

arr1= [[1 2]
 [3 4]]
arr2= [[5 6]
 [7 8]]
after concatenation =
[[1 2 5 6]
 [3 4 7 8]]


In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [4]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]


In [5]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print("hstack =", np.hstack((a,b)))

print("vstack =", np.vstack((a,b)))

a = np.array([[1],[2],[3]])

b = np.array([[4],[5],[6]])

print("hstack =", np.hstack((a,b)))

print("vstack =", np.vstack((a,b)))

hstack = [1 2 3 4 5 6]
vstack = [[1 2 3]
 [4 5 6]]
hstack = [[1 4]
 [2 5]
 [3 6]]
vstack = [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [6]:
a = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])

b = np.array([[7,8,9],[77,88,99],[777,888,999],[7777,8888,9999]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))

arr = np.concatenate((a, b), axis=0)

print("\n======next print======")

print("\n concatenate at axis 0=\n",arr)

arr1 = np.concatenate((a, b), axis=1)

print("\n======next print======")

print("\n concatenate at axis 1=\n",arr1)


hstack =
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]

======next print======

vstack =
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]

======next print======

 concatenate at axis 0=
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]

======next print======

 concatenate at axis 1=
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]


In [7]:
a= np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
b = np.array([7,8,9])
print(b)

[7 8 9]


In [9]:
c = np.array([[7,8,9]])
print(c)

[[7 8 9]]


In [10]:
np.append(a,c, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6])
np.concatenate((a,b))

array([1, 2, 3, 5, 6])

In [12]:
np.r_[a,b]

array([1, 2, 3, 5, 6])

In [13]:
a = np.array([1, 2,3])
b = np.array([5, 6,7])
np.stack([a,b]).reshape(-1)

array([1, 2, 3, 5, 6, 7])

In [14]:
a = np.array([1, 2,3])
b = np.array([5, 6,7])
np.stack([a,b])

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
a = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333]])

b = np.array([[7,8,9],[77,88,99],[777,888,999],[7777,8888,9999]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[   1    2    3    7    8    9]
 [  11   22   33   77   88   99]
 [ 111  222  333  777  888  999]
 [1111 2222 3333 7777 8888 9999]]

======next print======

vstack =
 [[   1    2    3]
 [  11   22   33]
 [ 111  222  333]
 [1111 2222 3333]
 [   7    8    9]
 [  77   88   99]
 [ 777  888  999]
 [7777 8888 9999]]


In [16]:
a = np.array([[1],[2],[3]])

b = np.array([[8],[9],[10]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[ 1  8]
 [ 2  9]
 [ 3 10]]

======next print======

vstack =
 [[ 1]
 [ 2]
 [ 3]
 [ 8]
 [ 9]
 [10]]


In [17]:
a = np.array([[1,2],[3,4]])

b = np.array([[5,6],[7,8]])

print("\nhstack =\n", np.hstack((a,b)))

print("\n======next print======")

print("\nvstack =\n", np.vstack((a,b)))


hstack =
 [[1 2 5 6]
 [3 4 7 8]]

======next print======

vstack =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [21]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
bb= np.array([[5, 6],[7,8]])
cc=b.T

print("vstack=",np.vstack((a,cc)))

print("hstack=",np.hstack((a,bb)))

vstack= [[1 2]
 [3 4]
 [5 6]]
hstack= [[1 2 5 6]
 [3 4 7 8]]


In [22]:
a = np.array((1,2,3))
b = np.array((7,8,9))
print(a)
print(b)

print("vstack\n")
print(np.vstack((a,b)))
print("concatenate\n")
print(np.concatenate([a.reshape(1,3),b.reshape(1,3)]))
print("stack\n")
print(np.stack((a,b),axis=1))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 1))
print("stack\n")
print(np.stack((a,b),axis=0))
print("concatenate\n")
print(np.concatenate((a.reshape(1,3),b.reshape(1,3)),axis = 0))

[1 2 3]
[7 8 9]
vstack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]
stack

[[1 7]
 [2 8]
 [3 9]]
concatenate

[[1 2 3 7 8 9]]
stack

[[1 2 3]
 [7 8 9]]
concatenate

[[1 2 3]
 [7 8 9]]


In [23]:
#numpy split
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2]) 

[1 2]
[3 4]
[5 6]


In [25]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2]) 



[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 9 10]
 [11 12]]


In [26]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 9 10]]


In [27]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[13 14 15]
 [16 17 18]]


In [28]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [29]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[13 14 15]
 [16 17 18]]


In [31]:
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step].
#If we don't pass start its considered 0
#If we don't pass end its considered length of array in that dimension
#If we don't pass step its considered 1


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:]) 

[5 6 7]


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4]) 

[1 2 3 4]


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-1])

[4 5 6]


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) 

[2 4]


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2]) 

[1 3 5 7]


In [37]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) 

[7 8 9]


In [38]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])

print(arr[2,0:2]) 

[11 12]


In [39]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[22,33,44,55,66]])

print(arr[0:3, 2]) #from both elements of array, return the value present at index 2

[ 3  8 44]


In [40]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4]) 

[[2 3 4]
 [7 8 9]]


In [41]:
#array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x) 

(array([3, 5, 6]),)


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x) 

(array([1, 3, 5, 7]),)


In [44]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x) 

(array([0, 2, 4, 6]),)


In [45]:
#The number 7 should be inserted on index 1 to remain the sort order.
#The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

import numpy as np

arr = np.array([6, 7, 18, 19])

x = np.searchsorted(arr,11)

print(x) 

2


In [46]:
import numpy as np

arr = np.array([6, 7, 18, 29])

x = np.searchsorted(arr, 19, side='right')

print(x) 

3


In [47]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x) 

[1 2 3]
